### ISSUE TITLE
Wrong waveform shape in R1 data ?

### ISSUE THREAD

**Issue by jlenain** [cta-observatory/ctapipe_io_nectarcam#43]
Hi,

Discussing with @kosack on testing our reader's compatibility with `ctapipe`, using the new test data from #26 , after hot fixing #41 using #42, we can get further with `ctapipe-process` but it seems the R1 waveforms have a wrong shape in `ctapipe_io_nectarcam`:

```
$ ctapipe-process --config base_config.yaml --config stage1_config.yaml --DataWriter.write_raw_waveforms=True --input dataset://NectarCAM.Run4717.0000.fits.fz  --output events.h5 --progress --log-level=INFO
2023-10-19 23:39:01,397 INFO [ctapipe.ctapipe-process] (tool.initialize): Loading config from '[PosixPath('/tmp/jlenain/scratch/Work/base_config.yaml'), PosixPath('/tmp/jlenain/scratch/Work/stage1_config.yaml')]'
2023-10-19 23:39:01,407 INFO [ctapipe.ctapipe-process] (tool.initialize): ctapipe version 0.19.1
2023-10-19 23:39:01,408 INFO [ctapipe.core.plugins] (plugins.detect_and_import_plugins): Loading ctapipe_io plugin: ctapipe_io_nectarcam:NectarCAMEventSource
2023-10-19 23:39:01,408 INFO [ctapipe.core.plugins] (plugins.detect_and_import_plugins): Entrypoint provides: <class 'ctapipe_io_nectarcam.NectarCAMEventSource'>
2023-10-19 23:39:01,408 INFO [ctapipe.core.plugins] (plugins.detect_and_import_plugins): Loading ctapipe_io plugin: ctapipe.io.hdf5eventsource:HDF5EventSource
2023-10-19 23:39:01,408 INFO [ctapipe.core.plugins] (plugins.detect_and_import_plugins): Entrypoint provides: <class 'ctapipe.io.hdf5eventsource.HDF5EventSource'>
2023-10-19 23:39:01,408 INFO [ctapipe.core.plugins] (plugins.detect_and_import_plugins): Loading ctapipe_io plugin: ctapipe.io.simteleventsource:SimTelEventSource
2023-10-19 23:39:01,408 INFO [ctapipe.core.plugins] (plugins.detect_and_import_plugins): Entrypoint provides: <class 'ctapipe.io.simteleventsource.SimTelEventSource'>
2023-10-19 23:39:01,412 INFO [ctapipe.ctapipe-process.NectarCAMEventSource] (eventsource.__init__): INPUT PATH = /home/jlenain/.cache/ctapipe/cccta-dataserver.in2p3.fr/data/ctapipe-test-data/v1.1.0/NectarCAM.Run4717.0000.fits.fz
2023-10-19 23:39:01,525 INFO [ctapipe.ctapipe-process.NectarCAMEventSource] (__init__.__init__): Read 1 input files
2023-10-19 23:39:01,630 WARNING [ctapipe.io.hdf5tableio.HDF5TableReader] (hdf5tableio._map_table_to_containers): Table /tel_0/calibration is missing column time_correction for field time_correction of container <class 'ctapipe.containers.WaveformCalibrationContainer'>. It will be skipped.
2023-10-19 23:39:01,630 WARNING [ctapipe.io.hdf5tableio.HDF5TableReader] (hdf5tableio._map_table_to_containers): Table /tel_0/calibration is missing column n_pe for field n_pe of container <class 'ctapipe.containers.WaveformCalibrationContainer'>. It will be skipped.
2023-10-19 23:39:01,640 WARNING [ctapipe.io.hdf5tableio.HDF5TableReader] (hdf5tableio._map_table_to_containers): Table /tel_0/flatfield is missing column charge_mean for field charge_mean of container <class 'ctapipe.containers.FlatFieldContainer'>. It will be skipped.
2023-10-19 23:39:01,640 WARNING [ctapipe.io.hdf5tableio.HDF5TableReader] (hdf5tableio._map_table_to_containers): Table /tel_0/flatfield is missing column charge_median for field charge_median of container <class 'ctapipe.containers.FlatFieldContainer'>. It will be skipped.
2023-10-19 23:39:01,640 WARNING [ctapipe.io.hdf5tableio.HDF5TableReader] (hdf5tableio._map_table_to_containers): Table /tel_0/flatfield is missing column charge_std for field charge_std of container <class 'ctapipe.containers.FlatFieldContainer'>. It will be skipped.
2023-10-19 23:39:01,640 WARNING [ctapipe.io.hdf5tableio.HDF5TableReader] (hdf5tableio._map_table_to_containers): Table /tel_0/flatfield is missing column time_mean for field time_mean of container <class 'ctapipe.containers.FlatFieldContainer'>. It will be skipped.
2023-10-19 23:39:01,640 WARNING [ctapipe.io.hdf5tableio.HDF5TableReader] (hdf5tableio._map_table_to_containers): Table /tel_0/flatfield is missing column time_median for field time_median of container <class 'ctapipe.containers.FlatFieldContainer'>. It will be skipped.
2023-10-19 23:39:01,640 WARNING [ctapipe.io.hdf5tableio.HDF5TableReader] (hdf5tableio._map_table_to_containers): Table /tel_0/flatfield is missing column time_std for field time_std of container <class 'ctapipe.containers.FlatFieldContainer'>. It will be skipped.
2023-10-19 23:39:01,640 WARNING [ctapipe.io.hdf5tableio.HDF5TableReader] (hdf5tableio._map_table_to_containers): Table /tel_0/flatfield is missing column relative_gain_median for field relative_gain_median of container <class 'ctapipe.containers.FlatFieldContainer'>. It will be skipped.
2023-10-19 23:39:01,640 WARNING [ctapipe.io.hdf5tableio.HDF5TableReader] (hdf5tableio._map_table_to_containers): Table /tel_0/flatfield is missing column relative_gain_std for field relative_gain_std of container <class 'ctapipe.containers.FlatFieldContainer'>. It will be skipped.
2023-10-19 23:39:01,640 WARNING [ctapipe.io.hdf5tableio.HDF5TableReader] (hdf5tableio._map_table_to_containers): Table /tel_0/flatfield is missing column relative_time_median for field relative_time_median of container <class 'ctapipe.containers.FlatFieldContainer'>. It will be skipped.
2023-10-19 23:39:01,640 WARNING [ctapipe.io.hdf5tableio.HDF5TableReader] (hdf5tableio._map_table_to_containers): Table /tel_0/flatfield is missing column charge_median_outliers for field charge_median_outliers of container <class 'ctapipe.containers.FlatFieldContainer'>. It will be skipped.
2023-10-19 23:39:01,640 WARNING [ctapipe.io.hdf5tableio.HDF5TableReader] (hdf5tableio._map_table_to_containers): Table /tel_0/flatfield is missing column charge_std_outliers for field charge_std_outliers of container <class 'ctapipe.containers.FlatFieldContainer'>. It will be skipped.
2023-10-19 23:39:01,640 WARNING [ctapipe.io.hdf5tableio.HDF5TableReader] (hdf5tableio._map_table_to_containers): Table /tel_0/flatfield is missing column time_median_outliers for field time_median_outliers of container <class 'ctapipe.containers.FlatFieldContainer'>. It will be skipped.
2023-10-19 23:39:01,643 WARNING [ctapipe.core.telescope_component] (telescope_component.attach_subarray): TelescopeParameter type argument '*FlashCam' did not match any known telescope types
2023-10-19 23:39:01,643 WARNING [ctapipe.core.telescope_component] (telescope_component.attach_subarray): TelescopeParameter type argument '*FlashCam' did not match any known telescope types
2023-10-19 23:39:01,649 WARNING [ctapipe.core.telescope_component] (telescope_component.attach_subarray): TelescopeParameter type argument 'LST*' did not match any known telescope types
2023-10-19 23:39:01,649 WARNING [ctapipe.core.telescope_component] (telescope_component.attach_subarray): TelescopeParameter type argument 'MST*FlashCam' did not match any known telescope types
2023-10-19 23:39:01,649 WARNING [ctapipe.core.telescope_component] (telescope_component.attach_subarray): TelescopeParameter type argument 'SST_ASTRI_CHEC' did not match any known telescope types
2023-10-19 23:39:01,650 WARNING [ctapipe.core.telescope_component] (telescope_component.attach_subarray): TelescopeParameter type argument 'LST*' did not match any known telescope types
2023-10-19 23:39:01,650 WARNING [ctapipe.core.telescope_component] (telescope_component.attach_subarray): TelescopeParameter type argument 'MST*FlashCam' did not match any known telescope types
2023-10-19 23:39:01,650 WARNING [ctapipe.core.telescope_component] (telescope_component.attach_subarray): TelescopeParameter type argument 'SST_ASTRI_CHEC' did not match any known telescope types
2023-10-19 23:39:01,712 WARNING [ctapipe.core.telescope_component] (telescope_component.attach_subarray): TelescopeParameter type argument 'LST_*' did not match any known telescope types
2023-10-19 23:39:01,713 WARNING [ctapipe.core.telescope_component] (telescope_component.attach_subarray): TelescopeParameter type argument 'SST_1M_*' did not match any known telescope types
2023-10-19 23:39:01,715 INFO [ctapipe.ctapipe-process] (process.start): (re)compute DL1: True
2023-10-19 23:39:01,715 INFO [ctapipe.ctapipe-process] (process.start): (re)compute DL2: False
2023-10-19 23:39:01,715 INFO [ctapipe.ctapipe-process] (process.start): compute muon parameters: False
2023-10-19 23:39:01,715 INFO [ctapipe.ctapipe-process] (subarray.info): Subarray : MST-0 subarray
2023-10-19 23:39:01,715 INFO [ctapipe.ctapipe-process] (subarray.info): Num Tels : 1
2023-10-19 23:39:01,716 INFO [ctapipe.ctapipe-process] (subarray.info): Footprint: 0.00 km2
2023-10-19 23:39:01,716 INFO [ctapipe.ctapipe-process] (subarray.info): 
2023-10-19 23:39:01,717 INFO [ctapipe.ctapipe-process] (subarray.info):        Type       Count Tel IDs
2023-10-19 23:39:01,717 INFO [ctapipe.ctapipe-process] (subarray.info): ----------------- ----- -------
2023-10-19 23:39:01,717 INFO [ctapipe.ctapipe-process] (subarray.info): MST_MST_NectarCam     1 0      
NectarCAMEventSource:   0%|                                                                                                                                                            | 0/15 [00:00<?, ?ev/s]
2023-10-19 23:39:01,725 ERROR [ctapipe.ctapipe-process] (tool.run): Caught unexpected exception: too many values to unpack (expected 2)
Traceback (most recent call last):
  File "/home/jlenain/local/opt/mambaforge/envs/nectar-dev/lib/python3.11/site-packages/ctapipe/core/tool.py", line 426, in run
    self.start()
  File "/home/jlenain/local/opt/mambaforge/envs/nectar-dev/lib/python3.11/site-packages/ctapipe/tools/process.py", line 312, in start
    self.calibrate(event)
  File "/home/jlenain/local/opt/mambaforge/envs/nectar-dev/lib/python3.11/site-packages/ctapipe/calib/camera/calibrator.py", line 287, in __call__
    self._calibrate_dl1(event, tel_id)
  File "/home/jlenain/local/opt/mambaforge/envs/nectar-dev/lib/python3.11/site-packages/ctapipe/calib/camera/calibrator.py", line 200, in _calibrate_dl1
    n_pixels, n_samples = waveforms.shape
    ^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)
2023-10-19 23:39:01,728 INFO [ctapipe.ctapipe-process] (tool.write_provenance): Output: /tmp/jlenain/scratch/Work/events.h5
2023-10-19 23:39:01,732 INFO [ctapipe.ctapipe-process.DataWriter] (datawriter.finish): Finishing output
2023-10-19 23:39:01,732 WARNING [ctapipe.ctapipe-process.DataWriter] (datawriter.finish): No events have been written to the output file
```

@kosack suggested that the `NectarCamEventSource` doesn't correctly apply the gain channel selection in the R0->R1 data conversion. Checking the [current code](https://github.com/cta-observatory/ctapipe_io_nectarcam/blob/cfc5bdb7d4e823909c20b56f92b8953b80afffd8/src/ctapipe_io_nectarcam/__init__.py#L904) with @kosack , this looks correct, but the error above suggests that the R1 waveforms still have a dimensionality of (N_channels, N_pixels, N_slices) rather than (N_pixels, N_slices).

@tibaldo , @vmarandon ?

Thanks !

**Comment by tibaldo** [comment]
Hi @jlenain, correct, people did not want gain correction applied by default because they wanted to test both HiG and LoG separately. There is an option to do so, though. One just needs to add to the configuration the option 
`select_gain=True`
There is also a `gain_selection_threshold` parameter that sets the threshold in ADC counts at which the switch Lo-Hi is done.

**Comment by kosack** [comment]
Now that I look at the code, I see you are not actually doing gain selection.  What you need to to do provide R1 waveforms is to run a `GainSelector`.  See [SimTelEventSource lines 289-290](https://github.com/cta-observatory/ctapipe/blob/7d32c650ffeb580b5923b6a5de708a25af92f27c/ctapipe/io/simteleventsource.py#L289-L290)

**Comment by tibaldo** [comment]
See my comment above. This is already implemented but not applied by default. The gain selection is applied at lines 100-102 of calibration.py. I think I have tested this in the past and it worked fine. There is also a test at lines 97... of test_nectarcameventsource.py.

**Comment by kosack** [comment]
You would then need in your ctapipe-process configuration file something like:
```yaml
NectarCamEventSource:
    gain_selector_type: ThresholdGainSelector  

    ThresholdGainSelector:
        # Threshold value in waveform sample units. If a waveform contains a>
        # above this threshold, use the low gain channel for that pixel.
        threshold: 4000
```
That way you can change the default value to be sure you are in the linear range before transitioning.

T

**Comment by sizun** [comment]
Or maybe @jlenain you would prefer test data with gain selection applied in the event builder?

**Comment by jlenain** [comment]
Sorry, re-opening this for our records.

So, sorry for my initial misunderstanding on the default behavior of `ctapipe_io_nectarcam` for the gain selection, but enabling it, I am happy to report that NectarCAM data can seamlessly be reconstructed and converted to DL1 (and thus potentially higher data levels) with `ctapipe`:

```
$ ctapipe-quickstart
[...]
$ ctapipe-process --config base_config.yaml --config stage1_config.yaml --DataWriter.write_raw_waveforms=True --input dataset://NectarCAM.Run4717.0001.fits.fz  --output events.h5 --progress --log-level=INFO --overwrite
2023-10-20 16:24:59,027 INFO [ctapipe.ctapipe-process] (tool.initialize): Loading config from '[PosixPath('/tmp/jlenain/scratch/Work/base_config.yaml'), PosixPath('/tmp/jlenain/scratch/Work/stage1_config.yaml')]'
2023-10-20 16:24:59,036 INFO [ctapipe.ctapipe-process] (tool.initialize): ctapipe version 0.19.1
2023-10-20 16:24:59,037 INFO [ctapipe.core.plugins] (plugins.detect_and_import_plugins): Loading ctapipe_io plugin: ctapipe_io_nectarcam:NectarCAMEventSource
2023-10-20 16:24:59,037 INFO [ctapipe.core.plugins] (plugins.detect_and_import_plugins): Entrypoint provides: <class 'ctapipe_io_nectarcam.NectarCAMEventSource'>
2023-10-20 16:24:59,037 INFO [ctapipe.core.plugins] (plugins.detect_and_import_plugins): Loading ctapipe_io plugin: ctapipe.io.hdf5eventsource:HDF5EventSource
2023-10-20 16:24:59,037 INFO [ctapipe.core.plugins] (plugins.detect_and_import_plugins): Entrypoint provides: <class 'ctapipe.io.hdf5eventsource.HDF5EventSource'>
2023-10-20 16:24:59,037 INFO [ctapipe.core.plugins] (plugins.detect_and_import_plugins): Loading ctapipe_io plugin: ctapipe.io.simteleventsource:SimTelEventSource
2023-10-20 16:24:59,037 INFO [ctapipe.core.plugins] (plugins.detect_and_import_plugins): Entrypoint provides: <class 'ctapipe.io.simteleventsource.SimTelEventSource'>
2023-10-20 16:24:59,041 INFO [ctapipe.ctapipe-process.NectarCAMEventSource] (eventsource.__init__): INPUT PATH = /home/jlenain/.cache/ctapipe/cccta-dataserver.in2p3.fr/data/ctapipe-test-data/v1.1.0/NectarCAM.Run4717.0001.fits.fz
2023-10-20 16:24:59,145 INFO [ctapipe.ctapipe-process.NectarCAMEventSource] (__init__.__init__): Read 1 input files
2023-10-20 16:24:59,272 WARNING [ctapipe.io.hdf5tableio.HDF5TableReader] (hdf5tableio._map_table_to_containers): Table /tel_0/calibration is missing column time_correction for field time_correction of container <class 'ctapipe.containers.WaveformCalibrationContainer'>. It will be skipped.
2023-10-20 16:24:59,272 WARNING [ctapipe.io.hdf5tableio.HDF5TableReader] (hdf5tableio._map_table_to_containers): Table /tel_0/calibration is missing column n_pe for field n_pe of container <class 'ctapipe.containers.WaveformCalibrationContainer'>. It will be skipped.
2023-10-20 16:24:59,280 WARNING [ctapipe.io.hdf5tableio.HDF5TableReader] (hdf5tableio._map_table_to_containers): Table /tel_0/flatfield is missing column charge_mean for field charge_mean of container <class 'ctapipe.containers.FlatFieldContainer'>. It will be skipped.
2023-10-20 16:24:59,280 WARNING [ctapipe.io.hdf5tableio.HDF5TableReader] (hdf5tableio._map_table_to_containers): Table /tel_0/flatfield is missing column charge_median for field charge_median of container <class 'ctapipe.containers.FlatFieldContainer'>. It will be skipped.
2023-10-20 16:24:59,280 WARNING [ctapipe.io.hdf5tableio.HDF5TableReader] (hdf5tableio._map_table_to_containers): Table /tel_0/flatfield is missing column charge_std for field charge_std of container <class 'ctapipe.containers.FlatFieldContainer'>. It will be skipped.
2023-10-20 16:24:59,281 WARNING [ctapipe.io.hdf5tableio.HDF5TableReader] (hdf5tableio._map_table_to_containers): Table /tel_0/flatfield is missing column time_mean for field time_mean of container <class 'ctapipe.containers.FlatFieldContainer'>. It will be skipped.
2023-10-20 16:24:59,281 WARNING [ctapipe.io.hdf5tableio.HDF5TableReader] (hdf5tableio._map_table_to_containers): Table /tel_0/flatfield is missing column time_median for field time_median of container <class 'ctapipe.containers.FlatFieldContainer'>. It will be skipped.
2023-10-20 16:24:59,281 WARNING [ctapipe.io.hdf5tableio.HDF5TableReader] (hdf5tableio._map_table_to_containers): Table /tel_0/flatfield is missing column time_std for field time_std of container <class 'ctapipe.containers.FlatFieldContainer'>. It will be skipped.
2023-10-20 16:24:59,281 WARNING [ctapipe.io.hdf5tableio.HDF5TableReader] (hdf5tableio._map_table_to_containers): Table /tel_0/flatfield is missing column relative_gain_median for field relative_gain_median of container <class 'ctapipe.containers.FlatFieldContainer'>. It will be skipped.
2023-10-20 16:24:59,281 WARNING [ctapipe.io.hdf5tableio.HDF5TableReader] (hdf5tableio._map_table_to_containers): Table /tel_0/flatfield is missing column relative_gain_std for field relative_gain_std of container <class 'ctapipe.containers.FlatFieldContainer'>. It will be skipped.
2023-10-20 16:24:59,281 WARNING [ctapipe.io.hdf5tableio.HDF5TableReader] (hdf5tableio._map_table_to_containers): Table /tel_0/flatfield is missing column relative_time_median for field relative_time_median of container <class 'ctapipe.containers.FlatFieldContainer'>. It will be skipped.
2023-10-20 16:24:59,281 WARNING [ctapipe.io.hdf5tableio.HDF5TableReader] (hdf5tableio._map_table_to_containers): Table /tel_0/flatfield is missing column charge_median_outliers for field charge_median_outliers of container <class 'ctapipe.containers.FlatFieldContainer'>. It will be skipped.
2023-10-20 16:24:59,281 WARNING [ctapipe.io.hdf5tableio.HDF5TableReader] (hdf5tableio._map_table_to_containers): Table /tel_0/flatfield is missing column charge_std_outliers for field charge_std_outliers of container <class 'ctapipe.containers.FlatFieldContainer'>. It will be skipped.
2023-10-20 16:24:59,281 WARNING [ctapipe.io.hdf5tableio.HDF5TableReader] (hdf5tableio._map_table_to_containers): Table /tel_0/flatfield is missing column time_median_outliers for field time_median_outliers of container <class 'ctapipe.containers.FlatFieldContainer'>. It will be skipped.
2023-10-20 16:24:59,285 WARNING [ctapipe.core.telescope_component] (telescope_component.attach_subarray): TelescopeParameter type argument 'LST*' did not match any known telescope types
2023-10-20 16:24:59,285 WARNING [ctapipe.core.telescope_component] (telescope_component.attach_subarray): TelescopeParameter type argument 'MST*FlashCam' did not match any known telescope types
2023-10-20 16:24:59,285 WARNING [ctapipe.core.telescope_component] (telescope_component.attach_subarray): TelescopeParameter type argument 'SST_ASTRI_CHEC' did not match any known telescope types
2023-10-20 16:24:59,285 WARNING [ctapipe.core.telescope_component] (telescope_component.attach_subarray): TelescopeParameter type argument 'LST*' did not match any known telescope types
2023-10-20 16:24:59,285 WARNING [ctapipe.core.telescope_component] (telescope_component.attach_subarray): TelescopeParameter type argument 'MST*FlashCam' did not match any known telescope types
2023-10-20 16:24:59,285 WARNING [ctapipe.core.telescope_component] (telescope_component.attach_subarray): TelescopeParameter type argument 'SST_ASTRI_CHEC' did not match any known telescope types
2023-10-20 16:24:59,299 WARNING [ctapipe.ctapipe-process.DataWriter] (datawriter._setup_output_path): Overwriting /tmp/jlenain/scratch/Work/events.h5
2023-10-20 16:24:59,350 WARNING [ctapipe.core.telescope_component] (telescope_component.attach_subarray): TelescopeParameter type argument 'LST_*' did not match any known telescope types
2023-10-20 16:24:59,351 WARNING [ctapipe.core.telescope_component] (telescope_component.attach_subarray): TelescopeParameter type argument 'SST_1M_*' did not match any known telescope types
2023-10-20 16:24:59,354 INFO [ctapipe.ctapipe-process] (process.start): (re)compute DL1: True
2023-10-20 16:24:59,354 INFO [ctapipe.ctapipe-process] (process.start): (re)compute DL2: False
2023-10-20 16:24:59,354 INFO [ctapipe.ctapipe-process] (process.start): compute muon parameters: False
2023-10-20 16:24:59,354 INFO [ctapipe.ctapipe-process] (subarray.info): Subarray : MST-0 subarray
2023-10-20 16:24:59,354 INFO [ctapipe.ctapipe-process] (subarray.info): Num Tels : 1
2023-10-20 16:24:59,354 INFO [ctapipe.ctapipe-process] (subarray.info): Footprint: 0.00 km2
2023-10-20 16:24:59,354 INFO [ctapipe.ctapipe-process] (subarray.info): 
2023-10-20 16:24:59,356 INFO [ctapipe.ctapipe-process] (subarray.info):        Type       Count Tel IDs
2023-10-20 16:24:59,356 INFO [ctapipe.ctapipe-process] (subarray.info): ----------------- ----- -------
2023-10-20 16:24:59,356 INFO [ctapipe.ctapipe-process] (subarray.info): MST_MST_NectarCam     1 0      
NectarCAMEventSource: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:14<00:00,  1.11ev/s]
2023-10-20 16:25:13,717 INFO [ctapipe.ctapipe-process] (tool.run): Finished: ctapipe-process
2023-10-20 16:25:13,718 INFO [ctapipe.ctapipe-process] (tool.write_provenance): Output: /tmp/jlenain/scratch/Work/events.h5
2023-10-20 16:25:13,722 INFO [ctapipe.ctapipe-process.DataWriter] (datawriter.finish): Finishing output
```
:smile: 

And... closing again.
