### ISSUE TITLE
`NectarCAMEventSource` not recognized as plugin of `ctapipe.io`

### ISSUE THREAD

**Issue by jlenain** [cta-observatory/ctapipe_io_nectarcam#52]
Reported by @tibaldo :

> Hi all, I installed ctapipe_io_nectarcam 0.1.5 to read the new data v6. Everything works fine if I use directly NectarCAMEventSource, but if I try to use the plugin discovery mechanism in ctapipe it does not seem to detect the NectarCAM event source. I copy below an example of error. Is this a mistake of mine of some sort?

```
>>> from [ctapipe.io](http://ctapipe.io/) import EventSource, EventSeeker 
>>> path='/Users/ltibaldo/CTA/NectarCam/data/runs/NectarCAM.Run5327.0000.fits.fz'
>>> reader=EventSource(input_url=path) 
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File "/Users/ltibaldo/anaconda3/envs/io_nectarcam_test/lib/python3.12/site-packages/ctapipe/io/eventsource.py", line 130, in __new__
  subcls = cls._find_compatible_source(input_url)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/Users/ltibaldo/anaconda3/envs/io_nectarcam_test/lib/python3.12/site-packages/ctapipe/io/eventsource.py", line 359, in _find_compatible_source
  raise ValueError(
ValueError: Cannot find compatible EventSource for 
	url:/Users/ltibaldo/CTA/NectarCam/data/runs/NectarCAM.Run5327.0000.fits.fz
in available EventSources:
	['HDF5EventSource', 'SimTelEventSource']
```

**Comment by jlenain** [comment]
As discussed on Slack, @vmarandon noted that one might need to add an `import ctapipe_io_nectarcam`.

However, this means we lost the plugin feature into `ctapipe.io`, presumably during the transition from `setup.py` installation approach to `pyproject.toml`.
